apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: goog-knowledge-graph
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: goog-knowledge-graph
    spec:
      containers:
      - name: jarvis-google-knowledge-graph
        image: lahsivjar/jarvis-google-knowledge-graph:latest
        env:
        - name: GOOG_KNOWLEDGE_GRAPH_API_KEY
          value: {{ google_knowledge_graph_api_key }}
        ports:
        - containerPort: 8080
